# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages
# Continuous Integration
name: CI on pull_request
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
  workflow_call:

jobs:
  setup:
    name: Install dependencies
    if: ${{ github.actor != 'dependabot[bot]' && !github.event.pull_request.head.repo.fork }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
      - name: echo
        run: echo "${{ hashFiles('yarn.lock') }}"
      - name: Cache node modules
        uses: actions/cache@v3
        id: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ hashFiles('yarn.lock') }}
      - name: Install dependencies
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: yarn install
  lint:
    name: Linting
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
      - name: Restore node modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ hashFiles('yarn.lock') }}
      - name: commitlint
        run: echo "${{ github.event.pull_request.title }}" | yarn commitlint
      - name: ESLint
        run: yarn run eslint
  test:
    name: Unit Test
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
      - name: Restore node modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ hashFiles('yarn.lock') }}
      - name: Cache test report
        id: cache-test-report
        uses: actions/cache@v3.0.2
        with:
          path: coverage/lcov.info
          key: test-report-${{ github.event.pull_request.head.sha }}
      - name: Test
        if: steps.cache-test-report.outputs.cache-hit != 'true'
        run: yarn test --coverage
  build:
    name: Build package
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
      - name: Restore Node.js modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ hashFiles('yarn.lock') }}
      - name: Build
        run: yarn build
